version: '2'

services:

  frontend:
    build: phpApache/frontend
    ports:
      - 20080:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./../:/app

  backend:
    build: phpApache/backend
    ports:
      - 21080:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./../:/app

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_DATABASE=yii2advanced
      - MYSQL_USER=yii2advanced
      - MYSQL_PASSWORD=secret

  #pgsql:
  #  image: postgres:9.5
  #  environment:
  #    - POSTGRES_DB=yii2advanced
  #    - POSTGRES_USER=yii2advanced
  #    - POSTGRES_PASSWORD=secret

  codecept:
    image: codeception/codeception:2.5.0
    depends_on:
      - chrome
      - firefox
    volumes:
      - ./../:/project
            
  chrome:
    image: 'selenium/standalone-chrome-debug:2.53.1'
    ports:
      - '5900'
    # workaround for Docker for Mac, see https://github.com/SeleniumHQ/docker-selenium/issues/227#issuecomment-224865735
    dns: 8.8.4.4
    environment:
      - no_proxy=localhost
  firefox:
    image: 'selenium/standalone-firefox-debug:2.53.1'
    ports:
      - '5900'
    # workaround for Docker for Mac, see https://github.com/SeleniumHQ/docker-selenium/issues/227#issuecomment-224865735
    dns: 8.8.4.4
    environment:
      - no_proxy=localhost
